---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-worker01-network-config-secret 
  namespace: openshift-machine-api
type: Opaque
stringData:
  nmstate: | 
    interfaces: 
    - name: enp4s0 
      type: ethernet
      mtu: 9000
      state: up
      ipv4:
        dhcp: true
        enabled: true
---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-worker01-bmc-secret
  namespace: openshift-machine-api
type: Opaque
data:
  username: username
  password: password
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: openshift-worker01
  namespace: openshift-machine-api
spec:
  online: true
  bootMACAddress: 52:54:00:de:8f:e4
  bootMode: legacy
  bmc:
    address: redfish-virtualmedia://emulator_ip:8002/redfish/v1/Systems/domain_uuid
    credentialsName: openshift-worker01-bmc-secret
    disableCertificateVerification: true
  customDeploy:
    method: install_coreos
  userData:
    name: worker-user-data-managed
    namespace: openshift-machine-api
  rootDeviceHints:
    deviceName: /dev/vda
  preprovisioningNetworkDataName: openshift-worker01-network-config-secret